M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date sön  4 sep 2022 18:40:54
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-04T18:40:54+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
%
G90
G05
T1
X4.216Y-2.5275
X4.216Y-2.6456
T0
M30
